### ISSUE TITLE
Unit 7) mutation function is not declared in the code 

### ISSUE THREAD

**Issue by booka24** [OUStudent/EvolutionaryComputationCourse#1]
Hello 

Thank you for such an amazing tutorial :) .

When I checked the code I found the mutation function called "mutation_1_n_z" but it's not declared anywhere in the code 

Could you please send me that part?

Best regards

**Comment by OUStudent** [comment]
Thank you for enjoying the tutorial! 

I justed added that function to the code! If you are wanting to apply the code to your own problems I highly suggest taking a look at following GitHub Repo where I've been applying all the concepts taught in that course in a library that can be easily utilized: https://github.com/OUStudent/EvolutionaryComputation

More specifically, take a look the following jupyter notebook where I used my python api library on the same dataset and achieved 89% accuracy!

https://github.com/OUStudent/EvolutionaryComputation/blob/master/EvolutionaryComputation/AutoML/examples/evolve_convolution_network_ciphar10_example.ipynb
